### ISSUE TITLE
IsWindowVisible() check fails without a delay

### ISSUE THREAD

**Issue by Abradoks** [Naseband/KillVolumeOSD#1]
Judging by the log, https://github.com/Naseband/KillVolumeOSD/blob/4bd781310a4e1983f550b57ae86b7ae74a774b12/VolumeOSD.cpp#L221 fails for me, even though the window does show up. Launching the program twice consecutively solves this.

Is that check even necessary for `destroy` and `noinput`?

Thank you for this program.

**Comment by Naseband** [comment]
In the case where the first run fails, is it launched at Windows startup/logon via shell:startup/a task, or do you launch it manually?

Does the log show that VolumeOSD found both the shell and OSD window handles?

I suspect what's happening is that either the explorer takes a tiny bit too long for the OSD to be created & shown, or that VolumeOSD is too quick with assuming it's not shown.

I think it's a simple fix by just waiting a tiny bit. In fact I had a short delay between sending the app command messages and trying to hide the OSD before the 1.2 version, but removed it because it didn't seem to be necessary in my case. I'll make a new release later today with a slightly more forgiving detection in non-daemon mode.

Regarding IsWindowVisible, due to the way the window flags work (and how explorer.exe handles the OSD window creation) I need to ensure that the window has actually been visible at least once. I could move the check to GetWindowLong (in the HideWindow function), but I'm pretty sure the end result would be the same.

**Comment by Abradoks** [comment]
> In the case where the first run fails, is it launched at Windows startup/logon via shell:startup/a task, or do you launch it manually?

Manually. After further testing, 1.2 works if launched right after restarting the explorer (when the OSD is shown for the first time), but fails if the OSD has been shown before. The delay in 1.1 solves the problem.

If I had to guess, 
https://github.com/Naseband/KillVolumeOSD/blob/4bd781310a4e1983f550b57ae86b7ae74a774b12/VolumeOSD.cpp#L215
gets triggered if the OSD is shown for the first time, adding the needed delay.

> Does the log show that VolumeOSD found both the shell and OSD window handles?

Yes. Only the `VolumeOSD Window hidden successfully` line is missing on failed attempts.

**Comment by Naseband** [comment]
That's strange that it also happens when launching manually. So far I have only seen this happening on windows startup (usually when using Windows' startup folder).

Either way, I made a new release with a simple retry mechanic which I hope solves this issue.

**Comment by Abradoks** [comment]
1.3 fixes it, thanks again for the program.

Works on the 1st try after restart, on the 2nd if the OSD has been shown before. So my previous guess was wrong.
